#!/usr/bin/env bash

# YOU NEED TO MODIFY YOUR INSTALLER-URL
# FQDN to Repository
installer_url="https://raw.githubusercontent.com/MarioWi/MultiCraft-JAR-Conf/java"
versions_path="$installer_url/versions.csv"
# *.jar.conf Files = <installer_url>/<conf_path>/
conf_path="minecraft"
# List of Servers exacly like in versions.csv needed for some install functions
listAPI="vanilla spigot paperspigot custom"
# Path to jar folder relativ to install.sh 
jar_path="./jar"
# List of Java install folders coresponding to required Java version in versions.csv
# Without trailing /java, it will add by install script.
java_list=( [Java8J9]="/usr/lib/jvm/adoptopenjdk-8-openj9-jre-amd64" 
            [Java8]="/usr/lib/jvm/adoptopenjdk-8-hotspot-jre-amd64" 
            [Java11]="/usr/lib/jvm/adoptopenjdk-11-hotspot-jre-amd64"
            [Java17]="/usr/lib/jvm/zulu17-ca-amd64" )